# Workflow to deploy current slides to GitHub Pages
name: Deploy slides to Pages

on:
  # Runs when pushes target the default branch
  push:
    branchs: ["main"]
  # Allow dispatch from the Actions tab
  workflow_dispatch:
  
# Set GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
  
# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true
  
jobs:
  # Single deploy job
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy
      id: deployment
      uses: actions/deploy-pages@v1